### ISSUE TITLE
Switch to ini for config

### ISSUE THREAD

**Issue by linted** [5aru/ScoreBot#3]
We currently are storing our server config in a yaml file, which requires a pip install of the parser. This is a completely legit way to do it, but I feel as though it may be difficult for users to edit if they are unfamiliar, as well as requireing more nonstandard dependencies. I want to propose the use of INI files instead. Currently most Linux projects use this standard to edit files (see systemd). There is also a [very convenient ini parser for python](https://docs.python.org/3.5/library/configparser.html) available as a default library.

Thoughts?

**Comment by 5aru** [comment]
Why is this necessary? Our user base, those who are hosting a CTF competition, can be expected to be reasonably capable with the technologies they are scoring.

**Comment by linted** [comment]
Config parser is a built in lib where as there is no built in lib for yaml parsing...

**Comment by linted** [comment]
resolved with recent pull
